# Generated by Django 2.2.4 on 2021-05-22 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_auto_20210521_2139'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmado', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripcionUsuario', to='usuarios.Usuario')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripcionCurso', to='cursos.Curso')),
            ],
        ),
    ]
