# Generated by Django 2.2.4 on 2021-05-23 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='participante',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscripcionUsuario', to='usuarios.Usuario'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='taller',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscripcionCurso', to='cursos.Curso'),
        ),
    ]
