# Generated by Django 2.2.4 on 2021-05-22 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20210521_1932'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Usuario',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
